export const user = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCEED: "LOGIN_SUCCEED",
  LOGIN_FAILED: "LOGIN_FAILED",
  
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCEED: "SIGNUP_SUCCEED",
  SIGNUP_FAILED: "SIGNUP_FAILED",

  AUTH_REQUEST: "AUTH_REQUEST",
  AUTH_SUCCEED: "AUTH_SUCCEED",
  AUTH_FAILED: "AUTH_FAILED"
}